filter:
    paths: ['src/*']

build:
    environment:
        php:
            version: 8.0
    tests:
        override:
            - php-scrutinizer-run --enable-security-analysis
            -   command: 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --config test/phpunit.xml --coverage-clover=test/clover.xml'
                coverage:
                    file: 'test/clover.xml'
                    format: 'clover'

tools:
    external_code_coverage: false