filter:
    paths:
        - 'src/*'
checks:
    php:
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true

coding_style:
    php: {  }

tools:
    external_code_coverage: false

build:
    environment:
        php:
            version: 7.4

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --configuration ./test/phpunit.xml --coverage-clover=test/clover.xml'
                coverage:
                    file: 'test/clover.xml'
                    format: 'clover'
